---
apiVersion: v1
kind: Pod
metadata:
        name: mysql  
        labels:
            name: mysql-pod
spec:
   containers:
      - image: mysql:5.6
        name: mysql
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: pass12345
         - name: MYSQL_DATABASE
           value: toolingdb
         - name: MYSQL_PASSWORD
           value: pass1234
         - name: MYSQL_USER
           value: admin
        ports:
          - containerPort: 3306
                     
